### ISSUE TITLE
Bubble_Sort

### ISSUE THREAD

**Issue by EverusLainus** [plpatil1/CW-Twitter-Trailblazers_099#2]
Bubble Sort Visualiser

- [x] Receive input array from the user.
- [x] Add animation in Bar Diagram to visualise bubble sort.
- [x] Visualise in various speed range.
- [x] Create aesthetic layout

**Comment by EverusLainus** [comment]
Done with basic structure to visualise bubble sort for user input.

**Comment by plpatil1** [comment]
Well Done!
